# Generated by Django 5.2.3 on 2025-06-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('creative_fields', models.JSONField()),
                ('portfolio_1', models.URLField(blank=True)),
                ('portfolio_2', models.URLField(blank=True)),
                ('portfolio_3', models.URLField(blank=True)),
            ],
        ),
    ]
